### PR TITLE
Bump version 0.1.3 -> 0.1.4

### PR DESCRIPTION
**Pull request by darinpope**
Signed-off-by: Darin Pope <darin@planetpope.com>

### CODE REVIEW

**Comment by Lawouach** [comment]
ah man, I'm sorry, I got carried away and missed this PR :(
My apologies. I have already done the change.

Mind closing this one?

**Comment by Lawouach** [comment]
I will try to clarify the contribution workflow somehow.

**Comment by darinpope** [comment]
closing...not needed

**Comment by Lawouach** [comment]
thansk and apologies for the extra work :(

**Pull request closed without merging**
